name: Portfolio

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/portfolio/**'
  pull_request:
    branches: [main]

jobs:
  build:
    name: Portfolio Build and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: bachitterch

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: 'yarn'

      - name: Install dependencies
        run: yarn install
      
      - name: Run Test
        run: yarn test --scope=bachitter.dev
        env:
          NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
          ABOUT_PAGE_ID: ${{ secrets.ABOUT_PAGE_ID }}
          NOW_PAGE_ID: ${{ secrets.NOW_PAGE_ID }}
          COLOPHON_PAGE_ID: ${{ secrets.COLOPHON_PAGE_ID }}
          BLOG_DATABASE_ID: ${{ secrets.BLOG_DATABASE_ID }}
          PROJECTS_DATABASE_ID: ${{ secrets.PROJECTS_DATABASE_ID }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
          REVUE_API_KEY: ${{ secrets.REVUE_API_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      
      - name: Deploy to Vercel Preview    
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.TURBO_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
